### ISSUE TITLE
upload slightly heavy file (ex : 600ko) fails

### ISSUE THREAD

**Issue by vulkanosaure** [karikera/ftp-kr#101]
I'm using the command upload all, it's working well, until it tries to upload a file around 600ko, and i get a loop of 
- Trying to connect to sftp:xxx
- upload /home/....
- Trying to connect to...

and it loops indefinitely like that

**Comment by karikera** [comment]
Oh.. 
You can change "connectionTimeout" to more longer!
{
 // other options ...
"connectionTimeout": 999999 // default is 6000(ms), can be longer, but i did not implement infinity timeout...
}

I made this extension to disconnect when command is stopped after 6000ms .
Because some ftp server is frozen sometimes...

**Comment by vulkanosaure** [comment]
Ah yes, i tried with a slow connexion. It works, thanks ! (Very good
extension, it changes my life !)

Le 22 juil. 2018 9:14 AM, "karikera" <notifications@github.com> a écrit :

Oh..
You can change "connectionTimeout" to more longer!
{
// other options ...
"connectionTimeout": 999999 // default is 6000(ms), can be longer, but i
did not implement infinity timeout...
}

I made this extension to disconnect when command is stopped after 6000ms .
Because some ftp server is frozen sometimes...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/karikera/ftp-kr/issues/101#issuecomment-406846351>, or mute
the thread
