### ISSUE TITLE
Upload Error when Remote Folder/File not exists

### ISSUE THREAD

**Issue by mvofreire** [karikera/ftp-kr#15]
When the saved file that does not exist on the remote server displays this error

[vs code]
![image](https://user-images.githubusercontent.com/4127341/29753355-3bb10c92-8b46-11e7-93e2-e11eee860251.png)

[LOG]
![image](https://user-images.githubusercontent.com/4127341/29753349-1e26c086-8b46-11e7-82ed-97e36525be99.png)

**Comment by karikera** [comment]
it looks like remotePath('/vecndor/dektrium/vii2-user/.github') directory is not existed,
do you need directory auto creating?..

**Comment by mnakalay** [comment]
That would be a great addition. Otherwise, we have to go to the remote, create the files and then we can upload. It defeats the purpose a little bit.

And frankly, of all the FTP sync tools I tried for Visual Studio, your is the only one that works (unless I'm a bit slow ) so with that option added, I think it would be perfect.

**Comment by blmbyd** [comment]
I agree we need directory auto creating :)

**Comment by karikera** [comment]
ok!  i will update it!

**Comment by mnakalay** [comment]
That's great, thank you!

**Comment by mvofreire** [comment]
Tanks Guys .. Works like a charm
